# Generated by Django 5.0.6 on 2025-02-16 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencias',
            fields=[
                ('numero', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date(2025, 2, 16))),
                ('laboratorio', models.CharField(max_length=80)),
                ('numOrdenador', models.IntegerField()),
                ('emailProfesor', models.EmailField(max_length=50)),
                ('resuelta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('numeroOrdenadores', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('contraseña', models.CharField(max_length=20)),
                ('laboratorio', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Resueltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroIncidencia', models.IntegerField()),
                ('emailProfesor', models.EmailField(max_length=50)),
                ('fecha', models.DateField(default=datetime.date(2025, 2, 16))),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
