# Generated by Django 5.0.6 on 2025-02-23 16:39

import Primera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.IntegerField(max_length=9)),
                ('ciclo', models.CharField(max_length=80)),
                ('dni', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=80)),
                ('profesorDni', models.CharField(max_length=80)),
                ('aulas', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('contraseña', models.CharField(max_length=20)),
                ('ciclo', models.CharField(max_length=80)),
                ('dni', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=80)),
                ('fechaEntrega', models.DateField(default=Primera.models.una_semana_despues)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
    ]
